# Seed categories
birth_control = Category.create(name: 'Birth Control')
emergency_contraception = Category.create(name: 'Emergency Contraception')
testing_kits = Category.create(name: 'Testing Kits')
otc_products = Category.create(name: 'OTC Products')

# Seed products
Product.create(name: 'Product 1', identifier: 'ABC123', quantity: 10, price: 19.99, instructions: 'Take one daily', category: birth_control)
Product.create(name: 'Product 2', identifier: 'DEF456', quantity: 5, price: 29.99, instructions: 'Take as needed', category: emergency_contraception)
Product.create(name: 'Product 3', identifier: 'GHI789', quantity: 1, price: 39.99, instructions: 'Follow included instructions', category: testing_kits)
Product.create(name: 'Product 4', identifier: 'JKL012', quantity: 20, price: 9.99, instructions: 'Use as directed', category: otc_products)

# Seed States
State.create(name: 'Alabama', offer_services: true, minimum_age: 18)
State.create(name: 'Alaska', offer_services: false, minimum_age: 18)
State.create(name: 'Arizona', offer_services: true, minimum_age: 18)
State.create(name: 'Arkansas', offer_services: true, minimum_age: 18)
State.create(name: 'California', offer_services: true, minimum_age: 18)
State.create(name: 'Colorado', offer_services: true, minimum_age: 18)
State.create(name: 'Connecticut', offer_services: true, minimum_age: 18)
State.create(name: 'Delaware', offer_services: true, minimum_age: 18)
State.create(name: 'Florida', offer_services: true, minimum_age: 18)
State.create(name: 'Georgia', offer_services: true, minimum_age: 18)
State.create(name: 'Hawaii', offer_services: true, minimum_age: 18)
State.create(name: 'Idaho', offer_services: true, minimum_age: 18)
State.create(name: 'Illinois', offer_services: true, minimum_age: 18)
State.create(name: 'Indiana', offer_services: true, minimum_age: 18)
State.create(name: 'Iowa', offer_services: true, minimum_age: 18)
State.create(name: 'Kansas', offer_services: true, minimum_age: 18)
State.create(name: 'Kentucky', offer_services: true, minimum_age: 18)
State.create(name: 'Louisiana', offer_services: true, minimum_age: 18)
State.create(name: 'Maine', offer_services: true, minimum_age: 18)
State.create(name: 'Maryland', offer_services: true, minimum_age: 18)
State.create(name: 'Massachusetts', offer_services: true, minimum_age: 18)
State.create(name: 'Michigan', offer_services: true, minimum_age: 18)
State.create(name: 'Minnesota', offer_services: true, minimum_age: 18)
State.create(name: 'Mississippi', offer_services: true, minimum_age: 18)
State.create(name: 'Missouri', offer_services: true, minimum_age: 18)
State.create(name: 'Montana', offer_services: true, minimum_age: 18)
State.create(name: 'Nebraska', offer_services: true, minimum_age: 18)
State.create(name: 'Nevada', offer_services: true, minimum_age: 18)
State.create(name: 'New Hampshire', offer_services: true, minimum_age: 18)
State.create(name: 'New Jersey', offer_services: true, minimum_age: 18)
State.create(name: 'New Mexico', offer_services: true, minimum_age: 18)
State.create(name: 'New York', offer_services: true, minimum_age: 18)
State.create(name: 'North Carolina', offer_services: true, minimum_age: 18)
State.create(name: 'North Dakota', offer_services: true, minimum_age: 18)
State.create(name: 'Ohio', offer_services: true, minimum_age: 18)
State.create(name: 'Oklahoma', offer_services: true, minimum_age: 18)
State.create(name: 'Oregon', offer_services: true, minimum_age: 18)
State.create(name: 'Pennsylvania', offer_services: true, minimum_age: 18)
State.create(name: 'Rhode Island', offer_services: true, minimum_age: 18)
State.create(name: 'South Dakota', offer_services: true, minimum_age: 18)
State.create(name: 'South Carolina', offer_services: true, minimum_age: 18)
State.create(name: 'Tennessee', offer_services: true, minimum_age: 18)
State.create(name: 'Texas', offer_services: true, minimum_age: 18)
State.create(name: 'Utah', offer_services: true, minimum_age: 18)
State.create(name: 'Vermont', offer_services: true, minimum_age: 18)
State.create(name: 'Virginia', offer_services: true, minimum_age: 18)
State.create(name: 'Washington', offer_services: true, minimum_age: 18)
State.create(name: 'West Virginia', offer_services: true, minimum_age: 18)
State.create(name: 'Wisconsin', offer_services: true, minimum_age: 18)
State.create(name: 'Wyoming', offer_services: true, minimum_age: 18)

